# -*- coding: utf-8 -*-
"""YOLOv5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mh7p8IHAllHychnmCbUzIeQXqOCaGItu
"""

from google.colab import drive
drive.mount('/content/drive/') 
import torch
from PIL import Image
import torchvision
import torchvision.transforms as transforms

import numpy as np
import torch
import math

import os
import glob
import json

cd /content/drive/MyDrive/YOLO_CLOTHES

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and 
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pip install rarfile

import rarfile
with rarfile.RarFile('/content/drive/MyDrive/YOLO_CLOTHES/clothes_dset/DEEPFASHION_YOLO.rar') as rf:
    rf.extractall('/content/drive/MyDrive/YOLO_CLOTHES/clothes_dset')

!curl -L "https://public.roboflow.com/ds/2Tb6yXY8l8?key=Eg82WpxUEr" > vehicles.zip

train_list = glob.glob(os.path.join('/content/drive/MyDrive/YOLO_CLOTHES/clothes_dset/DEEPFASHION_YOLO/train/images','*.jpg'))
# test_list = glob.glob(os.path.join('/content/drive/MyDrive/YOLO_SAMPLE/vehicles_open_image/test/images','*.jpg'))
# valid_list = glob.glob(os.path.join('/content/drive/MyDrive/YOLO_CLOTHES/clothes_dset/DEEPFASHION_YOLO/validation/images','*.jpg'))

print(len(train_list))

import yaml
config = {'train': '/content/drive/MyDrive/YOLO_CLOTHES/Small_dset/train',
         'val': '/content/drive/MyDrive/YOLO_CLOTHES/Small_dset/validation',
         'nc': 5,
         'names': ['short_top', 'long_top', 'short_outwear', 'long_outwear', 'vest']}

import yaml
with open("/content/drive/MyDrive/YOLO_CLOTHES/Small_dset/data.yaml","w") as file:
  yaml.dump(config,file,default_flow_style=False)

!python train.py --img 640 --batch 32 --epochs 20 --data '/content/drive/MyDrive/YOLO_CLOTHES/Small_dset/data.yaml' --weights yolov5s.pt

!python /content/drive/MyDrive/YOLO_CLOTHES/yolov5/detect.py --weights /content/drive/MyDrive/YOLO_CLOTHES/yolov5/runs/train/exp/weights/best.pt --img 416 --conf 0.1 --source /content/drive/MyDrive/YOLO_CLOTHES/Small_dset/custom_test

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/drive/MyDrive/YOLO_CLOTHES/yolov5/runs/detect/exp4/IMG_9615.jpg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")